//
//  SplashWorker.swift
//  Insocio
//
//  Created by Michael Westbrooks on 3/27/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SplashWorker
{
  func doSomeWork()
  {
  }
}
